version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: sibuh
      POSTGRES_PASSWORD: sibuh
      POSTGRES_DB: projects
    volumes:
      - ./data:/var/lib/postgresql/data
      # - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432