'use client';
// import type { Metadata } from "next";
import Image from "next/image";
// import Video from "next-video"

// export const metadata: Metadata = {
//   title: "arch website",
//   description: "Generated by create next app",
// };
interface Project {
  id:string,
  name:string
  description:string
  status:string
  imagePaths:string[]
  videoPaths:string[]
  createdAt:Date
  updatedAt:Date
}

import { useState, useEffect } from 'react'
 
export default function Projects() {
  const [data, setData] = useState<Project[]>([])
  const [isLoading, setLoading] = useState(true)
 
  useEffect(() => {
    fetch('/api/projects/list')
      .then((res) => res.json())
      .then((data) => {
        setData(data)
        setLoading(false)
      })
  }, [])
 
  if (isLoading) return <p>Loading...</p>
  if (!data) return <p>No profile data</p>
 
  return (
    <div className="grid grid-rows-[20px_1fr_20px] items-center justify-items-center">
      <p>Projects</p>
        <ul>
          {data.map((project)=>
            <div key={project.id} className="space-y-3">
                <h2>{project.name}</h2>
                <p>{project.description}</p>
                <p>{project.status}</p>
                <Image
                  className="rounded-md"
                  src={project.imagePaths[0]}
                  alt="Project picture"
                  width={450} 
                  height={500} 
                />
                <video 
                  className="rounded-md"
                  width={450}
                  height={500}
                  src={project.videoPaths[0]}>

                </video>
          </div>)}  
        </ul>
    </div>
  )
}

// export default function Home() {

//   return (
//     <div className="grid grid-rows-[20px_1fr_20px] items-center justify-items-center min-h-screen p-8 pb-20 gap-16 sm:p-20 font-[family-name:var(--font-geist-sans)]">
//       <p>Home page</p>
//       <Image
//       src={carImage}
//       alt="Picture of the car"
//        width={450} 
//        height={500} 
//     />
//     </div>
//   );
// }
